### ISSUE TITLE
macOS Sierra no longer trusts the puma-dev certificate

### ISSUE THREAD

**Issue by benubois** [puma/puma-dev#84] opened 2016-09-27 20:52 UTC
Hi,

After upgrading to Sierra, Safari and Chrome show an SSL error when trying to access sites served by puma-dev over https. Uninstalling and reinstalling puma-dev did not have any effect. Furthermore it appears that uninstalling does not remove the io.puma.dev directory and reinstalling does not prompt you to trust the certificate again.

I manually deleted `~/Application Support/io.puma.dev` and reinstalled which did prompt me to trust the certificate again, but still had invalid certificate errrors.

![screen shot 2016-09-27 at 1 52 12 pm](https://cloud.githubusercontent.com/assets/133809/18891326/9c1f60a4-84b9-11e6-8caf-f4dc73cd1ee0.png)

Thanks for puma-dev!

**Comment by gbonfant** [comment] 2016-09-28 11:22
I "fixed" this by opening the url with Safari, then selecting `Always trust this certificate` in the pop up window. Subsequent requests (from Chrome, curl, or whatever) will work as expected.

**Comment by navied** [comment] 2016-10-03 22:03
@gbonfant I tried that same method, but I found that it eventually goes back to not trusting it again.

**Comment by joshmanders** [comment] 2016-10-07 19:23
I fixed this issue by opening Keychain Access and moving the `Puma-dev CA` certificate into the `System` column under keychains then restarting my browser.

**Comment by rwilcox** [comment] 2016-10-07 20:15
@joshmanders good find! This trick worked for me: went from having to bypass the security once every 5 minutes to not being asked at all (granted, it's only been an hour, but...)

**Comment by joshmanders** [comment] 2016-10-07 20:45
It only worked for an hour for you? I've been going fine since doing it few hours ago.

**Comment by rwilcox** [comment] 2016-10-07 23:58
I mean it was working up until I had to stop coding, an hour later ;)

**Comment by koenpunt** [comment] 2016-10-08 09:06
The Keychain on macOS has been renamed, which could be the cause of this problem.

**Comment by attilagyorffy** [comment] 2016-11-29 09:50
Currently puma-dev uses a hardcoded `login.keychain` file to add the certificate however the login keychain file in macOS has been renamed as @koenpunt points out.

I think we should try to use the `security` tool to identify the right file during the setup. In the meanwhile you can use the following command:

```sh
security add-trusted-cert -k $(security login-keychain) ~/Library/Application\ Support/io.puma.dev/cert.pem
```

**Comment by attilagyorffy** [comment] 2016-12-22 17:19
I did create a patch that checks for the existence of the new keychain path and uses that if it's present. See #95

**Comment by danrabinowitz** [comment] 2016-12-29 06:40
Thanks! The original version from @attilagyorffy didn't quite work for me, but this one did:

```
security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem
```

**Comment by attilagyorffy** [comment] 2016-12-29 15:53
@danrabinowitz can i ask what did you get after having run my command mentioned above?

**Comment by danrabinowitz** [comment] 2016-12-30 04:23
Sure. :-)

```
~ $ security add-trusted-cert -k $(security login-keychain) ~/Library/Application\ Support/io.puma.dev/cert.pem
SecCertificateAddToKeychain: The specified keychain could not be found.
1:~ $ security login-keychain
    "/Users/danrabinowitz/Library/Keychains/login.keychain-db"
```

I decided to try (based only on a guess) using just the filename without the full path, and it worked.

**Comment by attilagyorffy** [comment] 2016-12-30 12:57
This is just a bare guess but your login keychain might be screwed. You see, the `security` command should list the login keychain where puma's cert should go. If you do not seem to have one, perhaps try to list the keychains your system is using:

```
$ security list-keychains
```

in my case, I'm getting the following:

```
    "/Users/attila/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```

I also wonder whether you would be willing to give me a little more help with cases like yours so that I could make the PR more robust, or at least improve it to provide better output to help people.

**Comment by danrabinowitz** [comment] 2017-01-01 03:24
I'm happy to help, @attilagyorffy. (I'm visiting family for the next couple of days, so I'll be less responsive than usual.)

On my computer, I get the following:
```
$ security list-keychains
    "/Users/danrabinowitz/Library/Keychains/login.keychain-db"
    "/Users/danrabinowitz/Library/Keychains/old-mbp-login.keychain-db"
    "/Library/Keychains/System.keychain"
```

I copied the keychain from my old MacBook Pro, which is why the middle entry is there. But I don't think that matters. Here is the output of the command you use in your code:
```
$ security login-keychain
    "/Users/danrabinowitz/Library/Keychains/login.keychain-db"
```

I tried just including that directly, and it failed. But when I used the filename only (login.keychain-db) it worked.

**Comment by olivierlacan** [comment] 2017-03-30 15:31
Any chance the version with this patch could be released @evanphx? We ended up building the latest dev version in hopes of solving this issue.

**Comment by lulalala** [comment] 2017-07-12 02:39
I just want to mention the Chrome error code `NET::ERR_CERT_AUTHORITY_INVALID` and `Your connection is not private` to make this issue more searchable.

The Keychain Access approached solved my issue on Chrome and Safari. Thanks.

Firefox is still having issue, showing `Your connection is not secure` `SEC_ERROR_UNKNOWN_ISSUER` though.

**Comment by ecielam** [comment] 2017-09-28 22:42
I am also getting an SSL issue with Ruby HTTP libraries, while Chrome is now fine after the keychain manipulation.

**Comment by attilagyorffy** [comment] 2017-10-10 18:20
@ecielam I suspect your Ruby installation is probably using the OpenSSL library from Homebrew, not the one that came with your system and has the keychain hooks. This means that you are going to need to make your OpenSSL aware of the puma-dev certificates.

To do this, you need to invoke the two commands:

```
$ cp ~/Library/Application\ Support/io.puma.dev/cert.pem /usr/local/etc/openssl/certs/io.puma.dev.pem
$ /usr/local/opt/openssl/bin/c_rehash
```

@evanphx I wonder, should we improve puma-dev by invoking these commands these during install? (given that the openssl install is in place of course)

**Comment by allaire** [comment] 2017-11-02 17:39
@attilagyorffy @danrabinowitz I completely uninstalled puma-dev and re-installed the latest released version, and I still got that Chrome warning.

Running `security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem` manually fixed it. I see that puma-dev run a similar command (https://github.com/puma/puma-dev/blob/085e195645a53b028489f93c7d08d608a93df598/dev/ssl_darwin.go#L41) but it didn't trust the certificate in my case. The difference seems to only be `-d -r trustRoot`.

**Comment by koenpunt** [comment] 2017-11-02 19:22
I believe the problem is also because of domain security policies, and that the .dev domain is configured to have HTST enabled by default, because the domain extension is owned by google

**Comment by allaire** [comment] 2017-11-02 19:25
@koenpunt I'm using the .dev domain extension as well and we've been using puma-dev without https for a while, we just switched today to https 😄

**Comment by attilagyorffy** [comment] 2017-11-05 15:38
Thanks for the heads up, @allaire. If I remember correctly (the PR was done a long time ago) the `-d` switch was necessary on macOS prior to High Sierra. (I may be mistaken, though and I cannot verify anymore - I've upgraded).

The `-d` switch is supposed to add the cert to all users (as in adding it to the root cert store) as you pointed out. I don't know why this wouldn't work for you.

**Comment by allaire** [comment] 2017-11-06 13:20
@attilagyorffy I don't think I'm an exception, and it looks like it's broken on High Sierra according to the Radar (my Macbook was clean install couple weeks ago).

Can you try on your side to completely uninstall puma-dev, uninstall certificates and re-install and see if you still get the chrome error?

**Comment by attilagyorffy** [comment] 2017-11-07 13:33
@allaire Sure thing. I'll find some time to do today and report back.

**Comment by konung** [comment] 2017-12-07 23:54
Just updated to Chrome on High Sierra and ran into the same issue. Again.  


Suggested solution from @joshmanders
 

> I fixed this issue by opening Keychain Access and moving the Puma-dev CA certificate into the System column under keychains then restarting my browser.

But there is one more step required.  Right-click on the Cert once it's in the Keychain, and go to Get Info. When there change the certificate to be trusted , like in this screenshot 

![screen shot 2017-12-07 at 17 52 58](https://user-images.githubusercontent.com/72493/33744602-a4aec5f0-db77-11e7-842d-fa97b16ee95d.png)

**Comment by attilagyorffy** [comment] 2017-12-10 18:15
I've removed the puma-dev certificate from the keychain and uninstalled puma-dev from Homebrew. I've also removed the `~/Library/Application\ Support/io.puma.dev` directory to ensure nothing was left. Then having reisntalled puma-dev from homebrew, I've done the setup and install commands:

```
❯ sudo puma-dev -setup
Password:
* Configuring /etc/resolver to be owned by attila

/private/etc/resolver 
❯ ll /etc/resolver/

/private/etc/resolver 
❯ puma-dev -install
* Adding certification to login keychain as trusted
! There is probably a dialog open that requires you to authenticate
* Certificates setup, ready for https operations!
* Use '/usr/local/Cellar/puma-dev/0.11/bin/puma-dev' as the location of puma-dev
* Installed puma-dev on ports: http 80, https 443

/private/etc/resolver 6s 
```

Everything seems fine on my side , Chrome (962.0.3202.94) won't complain about the certificates. I'm running High Sierra 10.13.2 (17C89). I've found is that the certificate in keychain seems to be Always Trusted by default (this is a screenshot without having to manually modify the certificates in keychain):

![screen shot 2017-12-10 at 19 10 34](https://user-images.githubusercontent.com/9091/33807936-86f0fe3e-ddde-11e7-85cb-eb8892a03ae3.png)

**Comment by kriskhaira** [comment] 2017-12-20 12:57
I had issues similar to the ones mentioned in this issue. After trying out the solutions including @joshmanders' one about moving/copying the certificate to the System keychain in Keychain Access, it got resolved in Chrome, Safari and Opera. 

However, I'm still having this problem in Firefox Quantum 57.0.1 (64-bit) on macOS—and the error is similar to the one faced by @lulalala.  Anyone know how to solve this? It seems like Firefox is being suspicious of certain "SSL issuers" like Puma-dev CA.

Full error:

> sample.dev uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates.
> An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER

I'm thinking of using the Advanced > Add Exception feature in the error page but it would be great if someone could point me to a better direction.

<img width="816" alt="screen shot 2017-12-20 at 8 56 00 pm" src="https://user-images.githubusercontent.com/80577/34208137-3cc1c284-e5c8-11e7-9379-68fae905541b.png">

**Comment by balinterdi** [comment] 2017-12-21 13:37
I'm not sure how important it is to have this resolved in FF, **if none of us developers use it for development** as it's only an issue in development. If we still need it to work there, your solution to treat it as an exception is a very good one.

**Comment by flaki** [comment] 2017-12-21 14:42
Not sure. Let's Encrypt won't work for your usecase?

---- On Thu, 21 Dec 2017 15:10:47 +0100 notifications@github.com wrote ----

@flaki you may have a better understanding of FF than I do. Do you happen to know what's causing FF to be 'picky' about self-signed certificates despite them being trusted in the system keychain?

**Comment by aarongray** [comment] 2017-12-30 00:16
If you can't get puma-dev to work, https://github.com/rchampourlier/tunnelss is a good alternative.

**Comment by dirtyhenry** [comment] 2018-02-16 15:45
I ran into this problem today after doing a full puma-dev reinstall:

* Remove certificates from keychain and file system
* Uninstall via homebrew

I also changed the domain from `.dev` to `.wip`, after reading @koenpunt's comment.
The CA was marked as trusted but I still had a warning of an insecure certificate when opening my URL with Safari. I'm running High Sierra 10.13.3.

I think a step-by-step guide on the proper way to manage these errors should appear on the README of the project. I feel a little intimated by this task as I'm by no mean an expert in certificates stuff and I'm not sure I took the right actions after reading this pretty verbose and work-in-progressy thread.

**Comment by andrewhavens** [comment] 2018-02-20 15:53
I was also running into an issue with trusting the puma-dev certificate authority in Firefox. Even though I had marked the certificate as "Always Trust" in Keychain Access, it seems like Firefox isn't respecting those settings. Here's how I manually added puma-dev as a trusted certificate authority. First, I symlinked the `cert.pem` file so that I could access it from the Finder file chooser dialog:

```
cd ~ && ln -s ~/Library/Application\ Support/io.puma.dev/cert.pem puma-dev.pem
```

Next, I navigated to the "Privacy and Security" Preferences screen in Firefox. Scroll down to the bottom and click the "View Certificates" button. On the "Authorities" tab, click the "Import..." button. Select the `puma-dev.pem` file that you just symlinked. This will open a dialog with checkboxes to check in order to trust the CA.

![screen shot 2018-02-20 at 7 37 23 am](https://user-images.githubusercontent.com/446392/36433987-c48458c4-1612-11e8-8ab3-63e6a1b08734.png)

**Comment by chrishough** [comment] 2018-03-11 04:24
that worked for me @joshmanders

**Comment by shanepinnell** [comment] 2018-04-06 00:06
For those wondering about Firefox, I believe Firefox uses its own certificate store, not the system's store.

**Comment by joallard** [comment] 2018-06-11 23:50
Thinking out loud about the security here, does trusting the CA mean that anyone can sign a certificate for any website and my system will trust it? Are there limitations to the cert? I'm not that well versed in the cert science here.

**Comment by okzea** [comment] 2018-08-22 15:52
@andrewhavens'  solution didn't work using symlink but copy paste worked : 
`sudo cp ~/Library/Application\ Support/io.puma.dev/cert.pem puma-dev.pem`

**Comment by richardonrails** [comment] 2018-08-26 19:52
I had some issues where puma-dev wasn't working in HTTPS even though a cert appeared in Keychain as Trusted, and I even uninstalled and reinstalled and ran `-setup` and `-install` again, and nothing worked for HTTPS until I ran this:

`security add-trusted-cert -k login.keychain-db ~/Library/Application\ Support/io.puma.dev/cert.pem`

Then everything started worked.

**Comment by nathanpalmer** [comment] 2019-04-25 13:14
It seems the reason the `security login-keychain` command isn't working is because of the quotes I'm getting in the output.

```
security login-keychain
```
>     "/Users/nathan/Library/Keychains/login.keychain-db"

They can be removed with a little bit of a longer command.

```
echo "$(security login-keychain | xargs | sed -e 's/^"//' -e 's/"$//')"
```
> /Users/nathan/Library/Keychains/login.keychain-db

and then adding it back to a one-liner

```
security add-trusted-cert -k $(security login-keychain | xargs | sed -e 's/^"//' -e 's/"$//') ~/Library/Application\ Support/io.puma.dev/cert.pem
```

**Comment by nonrational** [comment] 2020-03-04 14:35
I believe this is still an outstanding issue as of v0.13 on macOS Mojave. I'm working on some tests to verify the behavior, but `security add-trusted-cert` currently on master does not correctly trust the puma-dev CA. The `-d` flag to `security add-trusted-cert` meant to " Add to admin cert store; default is user" seems to be the issue.

**Closed** 2020-08-13 14:03 UTC
Labels: bug

**Comment by nonrational** [comment] 2021-03-31 15:55
AFAIK it has been resolved as of the most recent version. What version are you running? Can you see the `puma-dev` CA in Keychain Access? If you manually trust it with the GUI, does it work? Have you tried `-uninstall` and reinstalling to regenerate a new certificate?

**Comment by bradical** [comment] 2021-03-31 16:49
Ah, ok. It seems to work well on Safari but not on Firefox on MacOS Big Sur. Though perhaps that's a different problem? Do you all have a workaround for that?

**Comment by nonrational** [comment] 2021-03-31 17:01
Firefox controls its own CA store. You'll need to import your puma-dev CA manually or configure Firefox to use the macOS trust store. See https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox.
