### ISSUE TITLE
Force new CA to be generated

### ISSUE THREAD

**Issue by axelson** [puma/puma-dev#247] opened 2020-05-13 20:16 UTC
When I run `puma-dev -install` as part of the output I see:
> 2020/05/13 10:12:56 Existing valid puma-dev CA keypair found. Assuming previously trusted.

However, when I try to visit a puma-dev site I get an `Error code: SEC_ERROR_UNKNOWN_ISSUER` SSL error (and I see that the certificate is indeed signed by "Puma-dev Signed").

My hypothesis is that puma-dev thinks that the previous CA keypair was actually trusted but it is not. I previously had a most likely non-fully installed version of puma-dev 0.2, perhaps that's where the non-functional CA keypair found.

So is there a way to force `puma-dev -install` to generate a new CA keypair? Or possibly is the root cause a different issue?

**Comment by nonrational** [comment] 2020-05-14 00:57
There is currently a bug with keychain trust management, tracked in #84.  I have a PR drafted (https://github.com/puma/puma-dev/pull/246) to fix it, but am still trying to get the right level of test coverage. Testing keychain access in CI is brutal.

I suspect the problem is that the CA puma-dev generated has not been properly trusted. To manually trust it: 
1. Open Keychain Access, 
1. Find the "Puma-dev CA", 
1. Hit `⌘+i` to open the details panel
1. Select `Trust >`
1. Next to Secure Sockets Layer (SSL), select "Never Trust" and then back to "Always Trust."
![image](https://user-images.githubusercontent.com/550903/81880576-d2d5a200-955b-11ea-8325-62ba76bcbb93.png)

To remove the generated Puma-dev CA and regenerate a new CA (key and cert), delete the cert and key files (or the whole directory) at `$HOME/Library/ApplicationSupport/io.puma.dev`. This will cause `puma-dev -install` to generate a new CA cert/key. However, I expect it won't be trusted due to #84. Do report back!

**Comment by axelson** [comment] 2020-05-14 06:51
Totally didn't see #84 when searching for this!

Okay, so I got this working but I had to do more than just mark the certificate as trusted. It didn't work until I also moved the cert to the system certs, restarted my browser, and imported the certificate into the firefox authorities.

**Comment by nonrational** [comment] 2020-05-14 14:27
> Totally didn't see #84 when searching for this!

Understandable. It's super old. 

>  and imported the certificate into the firefox authorities.

AFAIK Firefox maintains its own trust store. Only Safari and Chrome use the macOS Keychain. So, even with the trust settings working correctly, Firefox won't get "hooked up" by default.

**Comment by nonrational** [comment] 2020-08-12 17:06
Resolving as duplicate in favor of #84

**Closed by nonrational** 2020-08-12 17:06 UTC
Labels: duplicate
