### ISSUE TITLE
Root CA issue

### ISSUE THREAD

**Issue by avioli** [puma/puma-dev#179] opened 2018-10-07 22:18 UTC
I'm getting an invalid certificate when trying to use a Puma Dev issued certificate.

It appears to expire at 3:50:06pm on the same day as the request.

Time of the request either matches the expiration or is before it. Unsure how to confirm this.

<img width="548" alt="screen shot 2018-10-07 at 3 54 57 pm" src="https://user-images.githubusercontent.com/524259/46578348-0bd99680-ca4a-11e8-8946-491203b2f021.png">
<img width="535" alt="screen shot 2018-10-07 at 3 55 41 pm" src="https://user-images.githubusercontent.com/524259/46578349-1136e100-ca4a-11e8-8339-1c5e5c5e74d6.png">

**Comment by a17levine** [comment] 2019-06-13 19:28
@avioli Try dragging the cert into the 'System' category of keychain access, that fixed it for me

**Comment by nonrational** [comment] 2020-03-04 20:05
Closing as duplicate of #138

**Closed by nonrational** 2020-03-04 20:05 UTC
