### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by annaswims** [puma/puma-dev#152] opened 2018-01-29 15:41 UTC
When I did `brew install puma/puma/puma-dev`
I saw: 
````
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/puma/homebrew-puma/puma-dev.rb:30:in `caveats'
Please report this to the puma/puma tap!
````

**Comment by wjp2013** [comment] 2018-02-02 03:38
me too.

* macOS 10.13.3
* Homebrew 1.5.2
* Homebrew/homebrew-core (git revision a6921; last commit 2018-02-01)

**Comment by nonrational** [comment] 2018-02-19 21:45
This is a duplicate of https://github.com/puma/homebrew-puma/issues/5

**Comment by evanphx** [comment] 2018-07-12 04:05
Fixed by the homebrew patch.

**Closed by evanphx** 2018-07-12 04:05 UTC
